#!/bin/bash

# of sbatch options.
#SBATCH --job-name=oral10
#SBATCH --nodes=1
#SBATCH --mem=20000
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=2
#SBATCH --partition=nih_s10
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shenxt1990@163.com
#SBATCH --account=mpsnyder
#SBATCH --time=165:00:00

#dir是过滤之后的数据存放路径
module load R
Rscript --vanilla brms_model_oral_vs_cytokine10.R
